### PR TITLE
docs: setup guide, hardware specs

### PR DESCRIPTION
**Pull request by mnh86**
Some docs if you'd like them:
- Setup guide for Windows and Arduino IDE v1
- Hardware specs summary (pulled pic and info from Twitter)

### CODE REVIEW

**Review by ExploratoryDevices — CHANGES_REQUESTED** [review]
Thanks!
For the analog sensor input, would be good to add the actual pinout (Tip = 5V, Ring = Sensor input (0-5V range), Shaft = Ground)

**Comment by mnh86** [comment]
> Thanks! For the analog sensor input, would be good to add the actual pinout (Tip = 5V, Ring = Sensor input (0-5V range), Shaft = Ground)

You're welcome! Pushed update to the `docs/hardware-specs.md` file with the sensor input info. 
Also added info for the RJ11 ports from https://github.com/tyrm/nimblestroker.

**Comment by mnh86** [comment]
I saw mention in another issue that it would be nice to have protocols documented in this repo perhaps? I'll take a stab at adding that to the hardware-specs doc.

**Comment by mnh86** [comment]
Any other things that might be good to add while I'm at it?

Perhaps add some links to these docs from the appropriate sections in the README?

**Review by ExploratoryDevices — APPROVED** [review]

**Review by ExploratoryDevices — APPROVED** [review]

**Review by ExploratoryDevices — APPROVED** [review]

**Review by ExploratoryDevices — APPROVED** [review]

**Review by ExploratoryDevices — APPROVED** [review]

**Pull request merged**
